version: "3.8"

services:
  redocly:
    image: redocly/redoc
    environment:
      SPEC_URL: ${REDOCLY_SPEC_URL}
    ports:
      - 5050:80

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
